INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, POSTAL, ADDRESS)
VALUES ('Jack','Black','jb@blabla.com', '94501','Columbus');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, POSTAL, ADDRESS)
VALUES ("John", "Doe", "jd@me.com", "12345", "San Francisco");

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, POSTAL, ADDRESS)
VALUES ("Mary", "Joseph", "mj@me.com", "23456", "Seattle");

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, POSTAL, ADDRESS)
VALUES ("Clark", "Kent", "ck@me.com", "22134", "New York");

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, POSTAL, ADDRESS)
VALUES ("Joanna", "D'Arc", "Jda@me.com", "34561", "Salem");

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, POSTAL, ADDRESS)
VALUES ("Abraham", "Lincoln", "al@me.com", "11122", "Washington DC");

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, POSTAL, ADDRESS)
VALUES ('Mina','Brasilia','mb@me.com','94102','San Francisco');

INSERT INTO CATEGORIES (NAME) VALUES ("House");
INSERT INTO CATEGORIES (NAME) VALUES ("Studio");
INSERT INTO CATEGORIES (NAME) VALUES ("Room");
INSERT INTO CATEGORIES (NAME) VALUES ("Appt 1 Bed");
INSERT INTO CATEGORIES (NAME) VALUES ("Appt 2 Bed");

INSERT INTO PLACES(LOCATION,CATEGORY_ID,OWNER_ID, DESCRIPTION, GUEST_ID,IMAGE_ID, AVAILABLE_DATE, AVAILABLE_PERIOD, OCCUPIED_DATE, OCCUPIED_PERIOD)
VALUES ('San Francisco',1,1,NULL,NULL,NULL,STR_TO_DATE('17,3,2019','%d,%m,%Y'),7,STR_TO_DATE('17,3,2019','%d,%m,%Y'),7);
INSERT INTO PLACES(LOCATION,CATEGORY_ID,OWNER_ID, DESCRIPTION, GUEST_ID,IMAGE_ID, AVAILABLE_DATE, AVAILABLE_PERIOD, OCCUPIED_DATE, OCCUPIED_PERIOD)
VALUES ('Paris',1,1,NULL,NULL,NULL,STR_TO_DATE('3,3,2019','%d,%m,%Y'),15,STR_TO_DATE('3,3,2019','%d,%m,%Y'),15);
INSERT INTO PLACES(LOCATION,CATEGORY_ID,OWNER_ID, DESCRIPTION, GUEST_ID,IMAGE_ID, AVAILABLE_DATE, AVAILABLE_PERIOD, OCCUPIED_DATE, OCCUPIED_PERIOD)
VALUES ('London',1,1,NULL,NULL,NULL,STR_TO_DATE('20,3,2019','%d,%m,%Y'),15,STR_TO_DATE('20,3,2019','%d,%m,%Y'),15);